# Generated by Django 5.0.6 on 2025-02-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radar',
            name='distancia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='radar',
            name='tempo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='radar',
            name='velocidade',
            field=models.IntegerField(),
        ),
    ]
